platform :osx, '10.8'

pod 'PMPKVObservation'
pod 'NSColor-Crayola'
pod 'JMSimpleDate'
pod 'ASHDatePicker'

pod 'BOAPI', :path => '~/Development/LocalPods/BOAPI'
pod 'DPWindow', :path => '~/Development/LocalPods/DPWindow'
pod 'DPKit', :path => '~/Development/LocalPods/DPKit'


pod 'DPOutlineView', :path => '~/Development/LocalPods/Controls/DPOutlineView'


#pod 'CALayer-Insertion', :path => '~/Development/LocalPods/CALayer-Insertion'
pod 'DPBackgroundTextField', :path => '~/Development/LocalPods/Controls/DPBackgroundTextField'


pod 'AutoCoding'