platform :osx, '10.8'

pod 'PMPKVObservation'
pod 'NSColor-Crayola'
pod 'JMSimpleDate'


pod 'BOAPI', :path => '~/Development/LocalPods/BOAPI'
pod 'DPWindow', :path => '~/Development/LocalPods/DPWindow'
pod 'DPKit', :path => '~/Development/LocalPods/DPKit'


#pod 'NSView-DPAutolayout', :path => '~/Development/LocalPods/NSView-DPAutolayout'
#pod 'JMSimpleDate', :podspec => '~/Development/LocalPods/JMSimpleDate'
#pod 'JMSimpleDate', :git => 'https://github.com/jamescmartinez/JMSimpleDate', :branch => 'master'

pod 'AutoCoding'